# Generated by Django 4.2.13 on 2024-06-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='audio',
            field=models.FileField(default=0, editable=False, upload_to='audio/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FinishBook',
        ),
    ]
