# Generated by Django 4.2.13 on 2024-06-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_pages_audio_delete_finishbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='audio',
            field=models.URLField(editable=False),
        ),
    ]
