# Generated by Django 4.2.13 on 2024-06-06 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_lastpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lastpage',
            old_name='name',
            new_name='book_id',
        ),
    ]
