# Generated by Django 4.2.13 on 2024-06-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_remove_books_page_remove_books_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
