# Generated by Django 4.2.13 on 2024-06-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_books_page_books_rate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='books',
            name='peoplerate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
